// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MushroomPocket.Migrations
{
    [DbContext(typeof(MushroomContext))]
    [Migration("20240523035008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("MushroomPocket.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Skill")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasDiscriminator<string>("CharacterType").HasValue("Character");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MushroomPocket.Daisy", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Daisy");
                });

            modelBuilder.Entity("MushroomPocket.Luigi", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Luigi");
                });

            modelBuilder.Entity("MushroomPocket.Mario", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Mario");
                });

            modelBuilder.Entity("MushroomPocket.Peach", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Peach");
                });

            modelBuilder.Entity("MushroomPocket.Waluigi", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Waluigi");
                });

            modelBuilder.Entity("MushroomPocket.Wario", b =>
                {
                    b.HasBaseType("MushroomPocket.Character");

                    b.HasDiscriminator().HasValue("Wario");
                });
#pragma warning restore 612, 618
        }
    }
}
